(ns cloudpassage-lib.fernet
  (:require [fernet.core :as fernet]))

(defn encrypt
  "given a token, encrypt a string using fernet. This does not set a TTL on
  the ciphertext.

  key - a key generated by `fernet.core/generate-key'
  message - a string that you would like to encrypt.

  returns a Fernet token which is a URL-safe base64 encoded series of bytes."
  [key message]
  (let [message-bytes (byte-array (map byte message))
        token (fernet/encrypt key message-bytes)]
    token))

(defn decrypt
  [key token]
  (let [message-bytes (fernet/decrypt key token)
        message (String. message-bytes)]
    message))
